export const database = {
  products: [
    {
      id: "1",
      name: "Navy blue Shirt",
      image: "/images/p1.png",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: "2",
      name: "Blue Shirt",
      image: "/images/p2.png",
      price: 250,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "3",
      name: "Yellow Shirt",
      image: "/images/p3.png",
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      id: "4",
      name: "Red Shirt",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
